version: "3.8"
# un nouveau commentaire
volumes:
  mariaimmo: #déclaration du volume pour la base

services:

  # container de bdd
  immobase: #nom de service
    container_name: baseimmo
    image: mariadb:latest
    ports:
      - '3309:3306'
    volumes:
      - mariaimmo:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: immoadmin
      MYSQL_DATABASE: immo
      MYSQL_USER: immouser
      MYSQL_PASSWORD: immouser

  # container php
  immophp:
    container_name: phpimmo
    build:
      context: ./php
#    user: "501:20"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - '9001:9000'
    environment:
      DEBUG: '1'
      PHP_DISPLAY_ERRORS: '1'
      PHP_POST_MAX_SIZE: "100M"
      PHP_UPLOAD_MAX_FILESIZE: "100M"
      TZ: UTC
    volumes:
      - ./app:/var/www/html
    depends_on:
      - immobase

  # service node
  immonode:
    tty: true
    container_name: nodeimmo
    build:
      context: ./node
    volumes:
      - ./app:/var/www/html
    restart: always
    environment:
      TZ: UTC
    depends_on:
      - immophp

  # server web
  immonginx:
    container_name: nginximmo
    image: nginx:stable-alpine
#    user: "501:20"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      TZ: UTC
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx/
    depends_on:
      - immophp
      - immobase
      - immonode